version: '2'

services:
  timelock.palantir.pt:
    image: palantirtechnologies/timelock-server-distribution
    command: [bash, -c, 'cp var/conf/timelock-postgres.yml var/conf/timelock.yml && service/bin/init.sh console']
    depends_on:
      - postgres
    ports:
      - "8421"
      - "8422"

  postgres:
    image: postgres:9.6-alpine
    environment:
       POSTGRES_PASSWORD: palantir
       POSTGRES_USER: palantir
       POSTGRES_DB: atlas
    ports:
      - "5432"

  ete1.palantir.pt:
    build: .
    command: [bash, -c, 'dockerize -timeout 120s -wait tcp://postgres:5432 && service/bin/init.sh start && tail -F var/log/atlasdb-ete-startup.log']
    ports:
      - "3828"
    environment:
      - ME=ete1
    depends_on:
      - postgres
      - timelock.palantir.pt
    volumes:
      - $CONFIG_FILE_MOUNTPOINT:/atlasdb-ete/atlasdb-ete-snapshot/var/conf/

  ete-cli.palantir.pt:
    build: .
    entrypoint: [bash, -c, 'cp var/conf/atlasdb-ete.no-leader.dbkvs.yml var/conf/atlasdb-ete.yml && "$$@"', --]
    command: exit
    depends_on:
      - ete1.palantir.pt
